version: '3.4'

  

services: 
  
  vncubuntu:
    build:  
      context: . 
    image: hbtlabs/vncubuntu
    container_name: vncubuntu
    ports:
      - 5901:5901

    volumes:
      - .:/vncubuntu
      - /tmp/vncubuntu:/tmp-vncubuntu
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/lxsession/LXDE:/root/.config/lxsession/LXDE
#      - ./config:/root/.config


