version: '3.4'

  

services: 
  
  vncubuntu:
    build:  
      context: . 
    image: hbtlabs/vncubuntu
    container_name: vncubuntu
# command: /functionshub/end2end/scripts/server-start.sh
# networks:
# - fhnet
    ports:
      - 5901:5901

    volumes:
      - .:/vncubuntu
      - /tmp/vncubuntu:/tmp-vncubuntu
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


